#!/usr/bin/env bash
cd "$(dirname "$0")"
source ./script/setup.sh
hyprspace_project_root="$PWD"

build_version="0.0.0-SNAPSHOT"
codesign_identity="-"
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --codesign-identity) codesign_identity="$2"; shift 2;;
        *) echo "Unknown option $1" > /dev/stderr; exit 1 ;;
    esac
done

#############
### BUILD ###
#############

./build-docs.sh --release
./build-shell-completion.sh

# Reject dirty input so generated release metadata can be restored safely.
./script/check-uncommitted-files.sh
hyprspace_generated_backup=$(mktemp -d)
hyprspace_generated_files=(
    Package.swift Sources/Common/versionGenerated.swift Sources/Common/gitHashGenerated.swift
    Sources/Common/cmdHelpGenerated.swift Sources/Cli/subcommandDescriptionsGenerated.swift
    xcode/AeroSpace.xcodeproj/project.pbxproj resources/AeroSpace.entitlements
)
for file in "${hyprspace_generated_files[@]}"; do
    mkdir -p "$hyprspace_generated_backup/$(dirname "$file")"
    cp "$file" "$hyprspace_generated_backup/$file"
done
restore_generated_files() {
    for file in "${hyprspace_generated_files[@]}"; do
        cp "$hyprspace_generated_backup/$file" "$hyprspace_project_root/$file"
    done
}
trap 'restore_generated_files; rm -rf "$hyprspace_generated_backup"' EXIT

./generate.sh
./script/check-uncommitted-files.sh
./generate.sh --build-version "$build_version" --codesign-identity "$codesign_identity" --generate-git-hash

swift_build_cli=(build -c release --arch arm64 --arch x86_64 --product aerospace)
swift "${swift_build_cli[@]}" -Xswiftc -warnings-as-errors # CLI
cli_bin_path="$(swift "${swift_build_cli[@]}" --show-bin-path)"

rm -rf .release && mkdir .release

cd ./xcode
    xcode_configuration="Release"
    xcodebuild -version
    xcodebuild-pretty ../.release/xcodebuild.log clean build \
        -scheme AeroSpace \
        -destination "generic/platform=macOS" \
        -configuration "$xcode_configuration" \
        -derivedDataPath .xcode-build
cd -

# Restore only files temporarily generated by this build.
restore_generated_files

cp -r "xcode/.xcode-build/Build/Products/$xcode_configuration/HyprSpace.app" .release
cp -r "$cli_bin_path/aerospace" .release

################
### SIGN CLI ###
################

codesign -s "$codesign_identity" .release/aerospace

################
### VALIDATE ###
################

expected_layout=$(cat <<EOF
.release/HyprSpace.app
.release/HyprSpace.app/Contents
.release/HyprSpace.app/Contents/_CodeSignature
.release/HyprSpace.app/Contents/_CodeSignature/CodeResources
.release/HyprSpace.app/Contents/MacOS
.release/HyprSpace.app/Contents/MacOS/HyprSpace
.release/HyprSpace.app/Contents/Resources
.release/HyprSpace.app/Contents/Resources/default-config.toml
.release/HyprSpace.app/Contents/Resources/AppIcon.icns
.release/HyprSpace.app/Contents/Resources/Assets.car
.release/HyprSpace.app/Contents/Resources/LICENSE.txt
$(find legal | sed 's|^legal|.release/HyprSpace.app/Contents/Resources/legal|')
.release/HyprSpace.app/Contents/Info.plist
.release/HyprSpace.app/Contents/PkgInfo
EOF
)

if test "$(printf '%s\n' "$expected_layout" | sort)" != "$(find .release/HyprSpace.app | sort)"; then
    echo "!!! Expect/Actual layout don't match !!!"
    find .release/HyprSpace.app
    exit 1
fi

check-universal-binary() {
    if ! file "$1" | grep --fixed-string -q "Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64"; then
        echo "$1 is not a universal binary"
        exit 1
    fi
}

check-contains-hash() {
    hash=$(git rev-parse HEAD)
    if ! strings "$1" | grep --fixed-string "$hash" > /dev/null; then
        echo "$1 doesn't contain $hash"
        exit 1
    fi
}

check-universal-binary .release/HyprSpace.app/Contents/MacOS/HyprSpace
check-universal-binary .release/aerospace

check-contains-hash .release/HyprSpace.app/Contents/MacOS/HyprSpace
check-contains-hash .release/aerospace

codesign -v .release/HyprSpace.app
codesign -v .release/aerospace
./script/check-bundled-licenses.sh .release/HyprSpace.app

############
### PACK ###
############

mkdir -p ".release/HyprSpace-v$build_version/manpage" && cp .man/*.1 ".release/HyprSpace-v$build_version/manpage"
cp -r ./legal ".release/HyprSpace-v$build_version/legal"
cp LICENSE.txt ".release/HyprSpace-v$build_version/LICENSE.txt"
cp -r .shell-completion ".release/HyprSpace-v$build_version/shell-completion"
cd .release
    mkdir -p "HyprSpace-v$build_version/bin" && cp -r aerospace "HyprSpace-v$build_version/bin"
    cp -r HyprSpace.app "HyprSpace-v$build_version"
    zip -r "HyprSpace-v$build_version.zip" "HyprSpace-v$build_version"
    shasum -a 256 "HyprSpace-v$build_version.zip" > "HyprSpace-v$build_version.zip.sha256"
cd -

#################
### DMG and local Homebrew casks ###
#################
./script/package-dmg.sh --build-version "$build_version"

for cask_name in hyprspace hyprspace-dev; do
    ./script/build-brew-cask.sh \
        --cask-name "$cask_name" \
        --zip-uri ".release/HyprSpace-v$build_version.zip" \
        --build-version "$build_version"
done
