#!/usr/bin/env bash
cd "$(dirname "$0")"
source ./script/setup.sh

# 1. It takes 300ms for cmd-help to generate. It's too long to run in build-debug.sh, that's why we ignore it
# 2. Grammar is not expected to change very often, that's why it's not regenerated by default
./generate.sh --ignore-xcodeproj --ignore-cmd-help
# SwiftPM can record the deployment target as the SDK version, disabling new system styling.
hyprspace_sdk_version="$(xcrun --sdk macosx --show-sdk-version)"
swift build --build-tests -Xlinker -platform_version -Xlinker macos \
    -Xlinker 13.0 -Xlinker "$hyprspace_sdk_version" "$@"

rm -rf .debug && mkdir .debug
cp -r .build/debug/aerospace .debug
cp -r .build/debug/AeroSpaceApp .debug
